---
name: placebo
on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  placebo:
    name: placebo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: true
